version: "3.8"
services:
  api-instagram:
    build:
      context: .
      platform: linux/amd64 # Especifica a arquitetura desejada

    image: mateusgomes1/pipegram:latest
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
    env_file:
      - .env
    restart: unless-stopped
